"""add_user_signal_status_table

Revision ID: f76d787cb8c8
Revises: 1f2671ff2c90
Create Date: 2025-12-02 09:26:47.258279+00:00
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76d787cb8c8'
down_revision = '1f2671ff2c90'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_signal_status',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('signal_id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(length=32), nullable=False),
        sa.Column('status', sa.Enum('ACTIVE', 'TRADED', 'REJECTED', 'EXPIRED', name='signalstatus'), nullable=False),
        sa.Column('marked_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'signal_id', name='uq_user_signal_status')
    )
    op.create_index('ix_user_signal_status_signal_id', 'user_signal_status', ['signal_id'], unique=False)
    op.create_index('ix_user_signal_status_user_id', 'user_signal_status', ['user_id'], unique=False)
    op.create_index('ix_user_signal_status_user_symbol', 'user_signal_status', ['user_id', 'symbol'], unique=False)
    op.create_index(op.f('ix_user_signal_status_status'), 'user_signal_status', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_signal_status_status'), table_name='user_signal_status')
    op.drop_index('ix_user_signal_status_user_symbol', table_name='user_signal_status')
    op.drop_index('ix_user_signal_status_user_id', table_name='user_signal_status')
    op.drop_index('ix_user_signal_status_signal_id', table_name='user_signal_status')
    op.drop_table('user_signal_status')
    # ### end Alembic commands ###
